CREATE TABLE guests (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 120),
  token_hash text NOT NULL UNIQUE CHECK (token_hash ~ '^[a-f0-9]{64}$'),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rsvps (
  guest_id integer PRIMARY KEY REFERENCES guests(id) ON DELETE RESTRICT,
  decision text NOT NULL CHECK (decision IN ('attending', 'declined')),
  message text NOT NULL DEFAULT '' CHECK (char_length(message) <= 500),
  submitted_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notification_status text NOT NULL DEFAULT 'pending' CHECK (notification_status IN ('pending', 'sent', 'failed')),
  notification_attempts integer NOT NULL DEFAULT 0,
  notification_sent_at timestamptz,
  notification_last_error text
);
